//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectComenzi
{
    using System;
    using System.Collections.Generic;
    
    public partial class comenzi_detaliu
    {
        public int id { get; set; }
        public int id_comanda { get; set; }
        public int id_produs { get; set; }
        public Nullable<decimal> cant { get; set; }
    
        public virtual comenzi comenzi { get; set; }
        public virtual produse produse { get; set; }
    }
}
