//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectComenzi
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class comenzi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comenzi()
        {
            this.comenzi_detaliu = new ObservableCollection<comenzi_detaliu>();
        }
    
        public int id { get; set; }
        public int id_partener { get; set; }
        public string nr { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual parteneri parteneri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comenzi_detaliu> comenzi_detaliu { get; set; }
    }
}
