//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectComenzi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comenzi_view
    {
        public int id { get; set; }
        public string nr { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string nume { get; set; }
        public string tel { get; set; }
        public Nullable<decimal> valoare { get; set; }
    }
}
