//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectComenzi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class comenziEntities : DbContext
    {
        public comenziEntities()
            : base("name=comenziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comenzi> comenzis { get; set; }
        public virtual DbSet<comenzi_detaliu> comenzi_detaliu { get; set; }
        public virtual DbSet<parteneri> parteneris { get; set; }
        public virtual DbSet<produse> produses { get; set; }
        public virtual DbSet<Comenzi_view> Comenzi_view { get; set; }
    }
}
