//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectComenzi
{
    using System;
    using System.Collections.Generic;
    
    public partial class produse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produse()
        {
            this.comenzi_detaliu = new HashSet<comenzi_detaliu>();
        }
    
        public int id { get; set; }
        public string denumire { get; set; }
        public Nullable<decimal> pret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comenzi_detaliu> comenzi_detaliu { get; set; }
    }
}
